import { Project } from "@/types";

export const projects: Project[] = [
    {
        id: "1",
        title: "Real-Time Voice AI Agent",
        category: "Conversational AI",
        image: "/projects/voice-agent.png",
        description: "Production-grade voice AI agent built on self-hosted LiveKit WebRTC infrastructure. Features a complete real-time pipeline: Sarvam STT for multilingual speech recognition, Groq LLM (Llama 3.3) with function tool calling for intelligent responses, and Sarvam TTS for natural voice synthesis. Integrated Langfuse observability for end-to-end tracing and evaluation.",
        tags: ["LiveKit", "Groq LLM", "Sarvam AI", "Langfuse", "WebRTC"],
        link: "https://github.com/sharan-raj-ai/VoiceAgent-AI",
        year: "2026",
        span: "md:col-span-2 md:row-span-2",
    },
    {
        id: "2",
        title: "Stock Price Prediction",
        category: "Machine Learning & Finance",
        image: "/projects/stock-prediction.png",
        description: "An ensemble prediction model that integrates historical time-series stock data with real-time sentiment analysis of financial news. Utilizes advanced regression techniques to correlate public sentiment shifts with market price movements.",
        tags: ["Scikit-Learn", "NLTK", "Matplotlib", "Python"],
        link: "https://github.com/Sai-sharann/Stock-Price-Prediction",
        year: "2025",
        span: "md:col-span-1 md:row-span-2",
    },
    {
        id: "3",
        title: "Dog Vision",
        category: "Computer Vision",
        image: "/projects/dog-vision.png",
        description: "An end-to-end multi-class image classifier trained on 10,000+ images from the Kaggle Dog Breed Identification dataset. Leverages MobileNetV2 with transfer learning to achieve high-speed breed recognition for 120 different classes.",
        tags: ["TensorFlow 2.x", "MobileNetV2", "Transfer Learning", "Kaggle"],
        link: "https://github.com/Sai-sharann/Dog-Vision",
        year: "2024",
        span: "md:col-span-1 md:row-span-3",
    },
    {
        id: "4",
        title: "VideoSearch AI",
        category: "Multi-Modal AI",
        image: "/projects/videosearch-ai.png",
        description: "A multi-modal Video RAG system with event-driven microservices architecture. Processes videos through an AI pipeline: frame extraction via FFmpeg, visual scene analysis using Llama 4 Vision, audio transcription with Whisper, and semantic embedding generation via Jina AI. Upload any video and search with natural language queries like 'find the part where they discuss revenue' or 'show me the drone shot of the forest' to instantly jump to exact timestamps.",
        tags: ["FastAPI", "Next.js", "Qdrant", "Groq AI", "Jina Embeddings"],
        link: "https://github.com/sharan-raj-ai/VideoSearch-AI",
        year: "2026",
        span: "md:col-span-2 md:row-span-3",
    },
    {
        id: "5",
        title: "Personalised Image Generation",
        category: "Generative AI",
        image: "/projects/personalised-image-gen.png",
        description: "High-fidelity facial attribute manipulation system using the pSp (pixel2style2pixel) framework built on StyleGAN. Implements latent space encoding for precise control over age, smile, and hairstyle with high identity preservation.",
        tags: ["StyleGAN", "pSp Model", "PyTorch", "GANS"],
        link: "https://github.com/Sai-sharann/Personalised-Image-Generation",
        year: "2025",
        span: "md:col-span-2 md:row-span-2",
    },
    {
        id: "6",
        title: "Heart Disease Classifier",
        category: "Healthcare AI",
        image: "/projects/heart-classifier.png",
        description: "Diagnostic pipeline for predicting heart disease using clinical parameters from the UCI Cleveland dataset. Evaluates multiple algorithms including Logistic Regression, K-Nearest Neighbors, and Random Forest to reach optimized accuracy metrics.",
        tags: ["Logistic Regression", "Random Forest", "EDA", "Healthcare"],
        link: "https://github.com/Sai-sharann/Heart-Disease-Classifier-",
        year: "2024",
        span: "md:col-span-1 md:row-span-2",
    },
];
