import { Project } from "@/types";

export const projects: Project[] = [
    {
        id: "1",
        title: "Personalised Image Generation",
        category: "Generative AI",
        image: "/projects/personalised-image-gen.png",
        description: "High-fidelity facial attribute manipulation system using the pSp (pixel2style2pixel) framework built on StyleGAN. Implements latent space encoding for precise control over age, smile, and hairstyle with high identity preservation.",
        tags: ["StyleGAN", "pSp Model", "PyTorch", "GANS"],
        link: "https://github.com/Sai-sharann/Personalised-Image-Generation",
        year: "2025",
        span: "md:col-span-2 md:row-span-3",
    },
    {
        id: "2",
        title: "Stock Price Prediction",
        category: "Machine Learning & Finance",
        image: "/projects/stock-prediction.png",
        description: "An ensemble prediction model that integrates historical time-series stock data with real-time sentiment analysis of financial news. Utilizes advanced regression techniques to correlate public sentiment shifts with market price movements.",
        tags: ["Scikit-Learn", "NLTK", "Matplotlib", "Python"],
        link: "https://github.com/Sai-sharann/Stock-Price-Prediction",
        year: "2025",
        span: "md:col-span-1 md:row-span-2",
    },
    {
        id: "3",
        title: "Dog Vision",
        category: "Computer Vision",
        image: "/projects/dog-vision.png",
        description: "An end-to-end multi-class image classifier trained on 10,000+ images from the Kaggle Dog Breed Identification dataset. Leverages MobileNetV2 with transfer learning to achieve high-speed breed recognition for 120 different classes.",
        tags: ["TensorFlow 2.x", "MobileNetV2", "Transfer Learning", "Kaggle"],
        link: "https://github.com/Sai-sharann/Dog-Vision",
        year: "2024",
        span: "md:col-span-1 md:row-span-3",
    },
    {
        id: "4",
        title: "Inwardly",
        category: "Web Development",
        image: "/projects/inwardly.png",
        description: "A professional response-driven corporate web application built during a Microsoft internship. Features modern glassmorphism UI components, fluid animations, and a focus on cross-platform accessibility and performance optimization.",
        tags: ["Frontend", "HTML5/CSS3", "Modern JS", "UI/UX"],
        link: "https://github.com/Sai-sharann/Inwardly",
        year: "2024",
        span: "md:col-span-2 md:row-span-2",
    },
    {
        id: "5",
        title: "Heart Disease Classifier",
        category: "Healthcare AI",
        image: "/projects/heart-classifier.png",
        description: "Diagnostic pipeline for predicting heart disease using clinical parameters from the UCI Cleveland dataset. Evaluates multiple algorithms including Logistic Regression, K-Nearest Neighbors, and Random Forest to reach optimized accuracy metrics.",
        tags: ["Logistic Regression", "Random Forest", "EDA", "Healthcare"],
        link: "https://github.com/Sai-sharann/Heart-Disease-Classifier-",
        year: "2024",
        span: "md:col-span-1 md:row-span-2",
    },
    {
        id: "6",
        title: "CODSOFT ML Showcase",
        category: "Machine Learning Tasks",
        image: "/projects/codsoft.png",
        description: "A comprehensive repository of machine learning and data science projects completed during the CODSOFT residency. Includes high-performance solutions for Titanic survival prediction, movie rating analysis, and credit card fraud detection.",
        tags: ["Supervised Learning", "Data Analysis", "Seaborn", "Numpy"],
        link: "https://github.com/Sai-sharann/CODSOFT",
        year: "2024",
        span: "md:col-span-2 md:row-span-2",
    },
];
